### ISSUE TITLE
Why is your twitter pointing to a scammer telegram group trying to steal your seed phrase ?

### ISSUE THREAD

**Issue by petarbelokonski** [SundaeSwap-finance/cardano-toolkit#9] opened 2022-01-27 14:41 UTC
Sundaeswap's website https://sundaeswap.finance links to their official twitter account https://twitter.com/SundaeSwap which in turn links to their official telegram group https://t.co/tNhjtAJSYx. This telegram group is a scam group - I asked for assistance and they asked me for my seed phrase. Can somebody please explain what is going on ?

**Comment by petarbelokonski** [comment] 2022-01-27 14:42
@Quantumplation Please explain

**Comment by petarbelokonski** [comment] 2022-01-27 16:49
Ok I see this is now updated to t.me/sundaeswapofficial. I hope this was a typo and the scammers took advantage of it. Please be transparent and explain how the issue occurred. Thanks

**Comment by Quantumplation** [comment] 2022-09-23 20:33
Hello,

I didn't realize people were opening issues against this repo, so apologies for never getting back to you.  I can't recall details, but yes, I believe the root cause was a typo which we fixed as soon as it was pointed out to us.

Closing this issue now.

**Closed as completed by Quantumplation** 2022-09-23 20:33 UTC
